name: sky_torch
version: '${project.version}'
main: com.heledron.sky_torch.SkyTorch
api-version: '1.20'

commands:
  items:
    description: Open the items menu
    usage: /items
  reload_config:
    description: Reload the configuration file
    usage: /reload_config
  preset:
    description: Select a preset
    usage: /preset <enum>
  scale:
    description: Scale the laser
    usage: /scale <double>